//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "switch_PinMux.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "driverlib/pwm.h"
#include "driverlib/interrupt.h"
#include "driverlib/timer.h"
#include "inc/tm4c123gh6pm.h"


//*****************************************************************************

 //about 2ms at 80Mhz
#define time 56666

//PWM frequency in hz
uint32_t freq = 100000;

uint32_t Period, dutyCycle;

void PortFunctionInit(void){
	
	 //Set system clock to 80Mhz
  SysCtlClockSet(SYSCTL_SYSDIV_2_5|SYSCTL_USE_PLL|SYSCTL_OSC_MAIN|SYSCTL_XTAL_16MHZ);
    

  Period = SysCtlClockGet()/freq/8 ;
  dutyCycle = Period-2; 

  /*
    Configure PF1 as T0CCP1
    Configure PF2 as T1CCP0
    Configure PF3 as T1CCP1
		Configure PB2 as T3CCP0
  */
  	   SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOC);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
  SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
  SysCtlDelay(3);
	GPIOPinConfigure(GPIO_PB2_T3CCP0);
  GPIOPinConfigure(GPIO_PF1_T0CCP1);  
  GPIOPinConfigure(GPIO_PF2_T1CCP0); 
  GPIOPinConfigure(GPIO_PF3_T1CCP1); 
  GPIOPinTypeTimer(GPIO_PORTF_BASE, GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3);
	GPIOPinTypeTimer(GPIO_PORTB_BASE,GPIO_PIN_2);   
  //


    //
    // Enable pin PA6 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, GPIO_PIN_6);		//Wifi module pin

    //
    // Enable pin PA5 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTA_BASE, GPIO_PIN_5);		//Wifi module pin

    //
    // Enable pin PA7 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTA_BASE, GPIO_PIN_7);		//Wifi module pin
		
    //
    // Enable pin PC7 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTC_BASE, GPIO_PIN_7);		//Turn Motor

    //
    // Enable pin PC6 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTC_BASE, GPIO_PIN_6);	//Turn Motor

    //
    // Enable pin PD0 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTD_BASE, GPIO_PIN_0);	//IR

    //
    // Enable pin PD1 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTD_BASE, GPIO_PIN_1);		//IR

    //
    // Enable pin PE1 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTE_BASE, GPIO_PIN_1);		//Merging Ping from the Wifi Module

  /*
    Configure timer 0 to split pair and timer B in PWM mode
    Set period and starting duty cycle.
  */
  SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER3); 	
  SysCtlDelay(3);
  TimerConfigure(TIMER0_BASE, TIMER_CFG_SPLIT_PAIR|TIMER_CFG_B_PWM);  
	TimerConfigure(TIMER3_BASE, TIMER_CFG_SPLIT_PAIR|TIMER_CFG_A_PWM);
	TimerLoadSet(TIMER3_BASE, TIMER_A, Period -1);                     
  TimerMatchSet(TIMER3_BASE, TIMER_A, dutyCycle); // PWM  
  TimerLoadSet(TIMER0_BASE, TIMER_B, Period -1);                     
  TimerMatchSet(TIMER0_BASE, TIMER_B, dutyCycle); // PWM  

  
  /*
    Configure timer 1 to split pair and timer A and B in PWM mode
    Set period and starting duty cycle.
  */  
  SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER1);    
  SysCtlDelay(3);
  TimerConfigure(TIMER1_BASE, TIMER_CFG_SPLIT_PAIR|TIMER_CFG_A_PWM|TIMER_CFG_B_PWM);   
  TimerLoadSet(TIMER1_BASE, TIMER_A, Period -1);
  TimerLoadSet(TIMER1_BASE, TIMER_B, Period -1);  
  TimerMatchSet(TIMER1_BASE, TIMER_A, dutyCycle);  
  TimerMatchSet(TIMER1_BASE, TIMER_B, dutyCycle); 

  //Turn on both timers
  TimerEnable(TIMER0_BASE, TIMER_B);
  TimerEnable(TIMER1_BASE, TIMER_A|TIMER_B);
	TimerEnable(TIMER3_BASE, TIMER_A);
	 
  
}

void PortAIntHandler(void)
{
	
		if(GPIOPinRead(GPIO_PORTA_BASE, GPIO_PIN_5) == 0x20)
		{
			GPIOIntClear(GPIO_PORTA_BASE, GPIO_PIN_5);
			TimerMatchSet(TIMER1_BASE, TIMER_A, Period-2);  //Halts the vehicles when the wifi sends a signal
      SysCtlDelay(time);
		}

		if(GPIOPinRead(GPIO_PORTA_BASE, GPIO_PIN_6) == 0x40)
		{
			GPIOIntClear(GPIO_PORTA_BASE, GPIO_PIN_6);
			TimerMatchSet(TIMER1_BASE, TIMER_A, (Period-2)/2);  //Moves the vehicles 
      SysCtlDelay(time);
		}
		if(GPIOPinRead(GPIO_PORTA_BASE, GPIO_PIN_7) == 0x80)
		{
			TimerMatchSet(TIMER1_BASE, TIMER_A, (Period-2)/4);  
      SysCtlDelay(time);
		}
}

void PortEIntHandler(void)			//Merging Right Handler
{
	GPIOIntClear(GPIO_PORTE_BASE, GPIO_PIN_1);
	
	int i = 0;
	
	GPIOPinWrite(GPIO_PORTC_BASE, GPIO_PIN_7, 0x80);
	
	if(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_1) != 0x00)  
	{
		i++;
		if(i > 2)			//Counts the number of times if crosses the white line which ends at 2 lines.
		{
			GPIOPinWrite(GPIO_PORTC_BASE, GPIO_PIN_7, 0x00); 	//Straighten wheels after merging
		}
	}
}

void Interrupt_init(void)
{
	
  IntEnable(INT_GPIOA);  							// enable interrupt 30 in NVIC (GPIOA)
	IntPrioritySet(INT_GPIOA, 0x01); 		// configure GPIOF interrupt priority as 1
	GPIO_PORTA_IM_R |= 0x03;   		// arm interrupt on PA5 and PA6 and PA7
	GPIO_PORTA_IS_R &= ~0x03;     // PA5 and PA6 and PA7 are edge-sensitive
  //GPIO_PORTD_IBE_R &= ~0x03;   	// PD0 and PD4 not both edges trigger 
  GPIO_PORTA_IEV_R &= ~0x03;  	// PA5 and PA6 and PA7 falling edge event
	
	IntEnable(INT_GPIOE);  							// enable interrupt 30 in NVIC (GPIOE)
	IntPrioritySet(INT_GPIOE, 0x00); 		// configure GPIOF interrupt priority as 0
	GPIO_PORTA_IM_R |= 0x01;   		// arm interrupt on PA5 and PA6 and PA7
	GPIO_PORTA_IS_R &= ~0x01;     // PA5 and PA6 and PA7 are edge-sensitive
  //GPIO_PORTD_IBE_R &= ~0x01;   	// PD0 and PD4 not both edges trigger 
  GPIO_PORTA_IEV_R &= ~0x01;  	// PA5 and PA6 and PA7 falling edge event
	
	
}

int main()
{
   PortFunctionInit();
	 Interrupt_init();
	
TimerMatchSet(TIMER1_BASE, TIMER_A, (Period-2)/4);  				//Intialize wheels to go straight
  while(1){
  
		if(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_0) != 0x00)		//Sensor tests for bright lines on the ground
	{
		GPIOPinWrite(GPIO_PORTC_BASE, GPIO_PIN_6, 0x40);				//Turns the wheels opposite of sensor
	}
		else
	{
		GPIOPinWrite(GPIO_PORTC_BASE, GPIO_PIN_6, 0x00);				//Straighten out wheels
	}
		if(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_1) != 0x00)    //Sensor tests for bright lines on the ground
	{
		GPIOPinWrite(GPIO_PORTC_BASE, GPIO_PIN_7, 0x80);				//Turns the wheels opposite of sensor
	}
	else
	{
		GPIOPinWrite(GPIO_PORTC_BASE, GPIO_PIN_7, 0x00);				//Straighten out wheels
	}
    
  }
  
}